DATA_VERSION = "2026-05-24-target-10-v1"
SAPIX_SOURCE = "2026年4月：前期合格力①：HP掲載表偏差値表 女子"


def exam_session(
    session_id,
    name,
    exam_date,
    slot,
    sapix80,
    sapix50,
    application_start="未定",
    application_end="未定",
    source_url="",
    check_status="SAPIX転記・要校対",
    note="",
    result_date="未定",
    procedure_deadline="未定",
):
    return {
        "id": session_id,
        "name": name,
        "exam_date": exam_date,
        "slot": slot,
        "hensachi": sapix80,
        "sapix_girls_80": sapix80,
        "sapix_girls_50": sapix50,
        "sapix_source": SAPIX_SOURCE,
        "application_start": application_start,
        "application_end": application_end,
        "result_date": result_date,
        "procedure_deadline": procedure_deadline,
        "source_url": source_url,
        "check_status": check_status,
        "note": note,
    }


def event(
    name,
    date,
    reservation_start="未定",
    event_type="学校説明会",
    time_slot="",
    source_url="",
    check_status="公式確認",
    note="",
):
    return {
        "name": name,
        "date": date,
        "reservation_start": reservation_start,
        "event_type": event_type,
        "time_slot": time_slot,
        "source_url": source_url,
        "check_status": check_status,
        "note": note,
    }


SCHOOLS = [
    {
        "id": "shibuya-shibuya",
        "name": "渋谷教育学園渋谷中学高等学校",
        "hensachi": 66,
        "hensachi_basis": "SAPIX女子80%最高値",
        "address": "東京都渋谷区渋谷1-21-18",
        "type": "共学",
        "nearest_station": "渋谷駅",
        "travel_time_from_koshigaya_laketown": 65,
        "homepage_url": "https://www.shibushibu.jp/",
        "photo_url": "https://www.shibushibu.jp/wp-content/uploads/2021/08/shibu_top_KV03.jpg",
        "photo_source_url": "https://www.shibushibu.jp/",
        "description": "「自調自考」を土台に、国際理解教育、第二外国語、海外研修、模擬国連などを通して多様な世界と出会う機会を設けている学校。",
        "tags": ["国際化", "英語教育", "留学機会", "探究学習", "中高一貫"],
        "events": [
            event("飛龍祭", "2026-09-11", "2026-07-中旬頃", "文化祭", "12:45-15:30", "https://www.shibushibu.jp/admission/event_schedule.html"),
            event("飛龍祭", "2026-09-12", "2026-07-中旬頃", "文化祭", "9:00-12:00 / 12:45-15:30", "https://www.shibushibu.jp/admission/event_schedule.html"),
            event("第1回 学校説明会", "2026-10-17", "2026-09-中旬頃", "学校説明会", "14:15-15:30", "https://www.shibushibu.jp/admission/event_schedule.html"),
            event("第2回 学校説明会", "2026-11-21", "2026-09-中旬頃", "学校説明会", "14:15-15:30", "https://www.shibushibu.jp/admission/event_schedule.html"),
        ],
        "exam_sessions": [
            exam_session("shibuya-shibuya-feb01-am", "第1回入学試験", "2027-02-01", "AM", 63, 62, "2027-01-10 10:00", "2027-01-28 14:59", "https://www.shibushibu.jp/admission/detail.html", "公式日程確認・偏差値要校対"),
            exam_session("shibuya-shibuya-feb02-am", "第2回入学試験", "2027-02-02", "AM", 64, 63, "2027-01-10 10:00", "2027-01-28 14:59", "https://www.shibushibu.jp/admission/detail.html", "公式日程確認・偏差値要校対"),
            exam_session("shibuya-shibuya-feb05-am", "第3回入学試験", "2027-02-05", "AM", 66, 64, "2027-01-10 10:00", "2027-02-04 23:59", "https://www.shibushibu.jp/admission/detail.html", "公式日程確認・偏差値要校対"),
        ],
        "notes": "出願期間は公式募集要項で確認済み。偏差値はSAPIX女子表からの転記候補。",
    },
    {
        "id": "shibuya-makuhari",
        "name": "渋谷教育学園幕張中学校",
        "hensachi": 65,
        "hensachi_basis": "SAPIX女子80%最高値",
        "address": "千葉県千葉市美浜区若葉1-3",
        "type": "共学",
        "nearest_station": "海浜幕張駅",
        "travel_time_from_koshigaya_laketown": 72,
        "homepage_url": "https://www.shibumaku.jp/",
        "photo_url": "https://www.shibumaku.jp/wp-content/uploads/2026/05/IMG_7489-1024x682.jpg",
        "photo_source_url": "https://www.shibumaku.jp/",
        "description": "「自調自考」を教育目標に掲げ、海外留学・海外大学進学サポート、帰国生・留学生との交流など、国際教育を重視する中高一貫校。",
        "tags": ["国際化", "英語教育", "留学機会", "探究学習", "中高一貫"],
        "events": [
            event("中学校入試説明会", "2026-11-07", "未定", "入試説明会", "未定", "https://www.shibumaku.jp/admissions/meeting-2-3-2/", "要再確認", "2026年度ページ公開後に更新"),
        ],
        "exam_sessions": [
            exam_session("shibuya-makuhari-jan22-am", "第1次入学試験", "2027-01-22", "AM", 64, 61, source_url="https://www.shibumaku.jp/admissions/", note="公式2027募集要項公開後に出願期間を確認"),
            exam_session("shibuya-makuhari-feb02-am", "第2次入学試験", "2027-02-02", "AM", 65, 62, source_url="https://www.shibumaku.jp/admissions/", note="公式2027募集要項公開後に出願期間を確認"),
        ],
        "notes": "2027年度募集要項・説明会詳細は公式公開後に月次更新対象。",
    },
    {
        "id": "hiroo-gakuen",
        "name": "広尾学園中学校",
        "hensachi": 62,
        "hensachi_basis": "SAPIX女子80%最高値",
        "address": "東京都港区南麻布5-1-14",
        "type": "共学",
        "nearest_station": "広尾駅",
        "travel_time_from_koshigaya_laketown": 61,
        "homepage_url": "https://www.hiroogakuen.ed.jp/",
        "photo_url": "https://www.hiroogakuen.ed.jp/img/topimg/topimg-1773366142137660.jpg",
        "photo_source_url": "https://www.hiroogakuen.ed.jp/",
        "description": "本科、医進・サイエンス、インターナショナルの3コースを設置。国際教育、理系教育、先端的なキャリア教育を比較しやすい学校。",
        "tags": ["国際化", "英語教育", "留学機会", "医進", "サイエンス", "中高一貫"],
        "events": [
            event("第2回授業体験会・学校説明会", "2026-09-06", "2026-08-08 10:00", "授業体験会", "午前 / 午後", "https://www.hiroogakuen.ed.jp/junior/j_setumeikai.html"),
            event("第3回授業体験会・学校説明会", "2026-10-11", "2026-09-19 10:00", "授業体験会", "午前 / 午後", "https://www.hiroogakuen.ed.jp/junior/j_setumeikai.html"),
            event("第1回入試傾向説明会", "2026-11-09", "2026-10-17 10:00", "入試傾向説明会", "午前 / 午後", "https://www.hiroogakuen.ed.jp/junior/j_setumeikai.html"),
            event("第2回入試傾向説明会", "2026-12-13", "2026-11-21 10:00", "入試傾向説明会", "午前 / 午後", "https://www.hiroogakuen.ed.jp/junior/j_setumeikai.html"),
        ],
        "exam_sessions": [
            exam_session("hiroo-gakuen-feb01-am-honka1", "本科 第1回", "2027-02-01", "AM", 58, 55, source_url="https://www.hiroogakuen.ed.jp/junior/j_boshuyoko.html"),
            exam_session("hiroo-gakuen-feb01-pm-honka2", "本科 第2回", "2027-02-01", "PM", 59, 57, source_url="https://www.hiroogakuen.ed.jp/junior/j_boshuyoko.html"),
            exam_session("hiroo-gakuen-feb01-pm-isg2", "インターナショナルSG 第2回", "2027-02-01", "PM", 61, 58, source_url="https://www.hiroogakuen.ed.jp/junior/j_boshuyoko.html"),
            exam_session("hiroo-gakuen-feb02-pm-med", "医進・サイエンス回", "2027-02-02", "PM", 62, 58, source_url="https://www.hiroogakuen.ed.jp/junior/j_boshuyoko.html"),
            exam_session("hiroo-gakuen-feb05-am-honka3", "本科 第3回", "2027-02-05", "AM", 57, 55, source_url="https://www.hiroogakuen.ed.jp/junior/j_boshuyoko.html"),
            exam_session("hiroo-gakuen-feb05-am-isg3", "インターナショナルSG 第3回", "2027-02-05", "AM", 58, 55, source_url="https://www.hiroogakuen.ed.jp/junior/j_boshuyoko.html"),
        ],
        "notes": "説明会日程は公式掲載から転記。入試日程はSAPIX表ベースで、公式募集要項の最新版公開後に校対。",
    },
    {
        "id": "ichikawa",
        "name": "市川中学校",
        "hensachi": 59,
        "hensachi_basis": "SAPIX女子80%最高値",
        "address": "千葉県市川市本北方2-38-1",
        "type": "共学",
        "nearest_station": "本八幡駅",
        "travel_time_from_koshigaya_laketown": 54,
        "homepage_url": "https://www.ichigaku.ac.jp/",
        "photo_url": "https://www.ichigaku.ac.jp/html/top/images/bg_features01.jpg",
        "photo_source_url": "https://www.ichigaku.ac.jp/",
        "description": "SSH、国際研修、土曜講座、市川アカデメイアなど、教科学習と探究・国際理解の両面を確認しやすい中高一貫校。",
        "tags": ["英語教育", "理科強", "探究学習", "中高一貫", "国際化"],
        "events": [
            event("学校説明会・入試説明会", "2026-10-01", "未定", "説明会", "未定", "https://www.ichigaku.ac.jp/junior-exam/", "要再確認", "公式イベントページ更新後に詳細化"),
        ],
        "exam_sessions": [
            exam_session("ichikawa-jan20-am", "第1回入学試験", "2027-01-20", "AM", 58, 55, source_url="https://www.ichigaku.ac.jp/junior-exam/guideline/"),
            exam_session("ichikawa-feb04-am", "第2回入学試験", "2027-02-04", "AM", 59, 56, source_url="https://www.ichigaku.ac.jp/junior-exam/guideline/"),
        ],
        "notes": "2027年度募集要項PDFの細部は月次更新時に再確認。",
    },
    {
        "id": "sakae-higashi",
        "name": "栄東中学校・高等学校",
        "hensachi": 59,
        "hensachi_basis": "SAPIX女子80%最高値",
        "address": "埼玉県さいたま市見沼区砂町2-77",
        "type": "共学",
        "nearest_station": "東大宮駅",
        "travel_time_from_koshigaya_laketown": 45,
        "homepage_url": "https://www.sakaehigashi.ed.jp/index.html",
        "photo_url": "https://www.sakaehigashi.ed.jp/cms_img/ad2a253a53786fd1e30dde52fef39f21f53f72d8.jpg",
        "photo_source_url": "https://www.sakaehigashi.ed.jp/index.html",
        "description": "「生きる力」を育むことを掲げ、アクティブ・ラーニング、国際部、大学合格実績を比較しやすい埼玉の中高一貫校。",
        "tags": ["英語教育", "理科強", "探究学習", "中高一貫", "進学実績"],
        "events": [
            event("第1回 学校説明会", "2026-05-30", "2026-05-11 10:00", "学校説明会", "10:00-", "https://www.sakaehigashi.ed.jp/exam/j_event.html"),
            event("第2回 学校説明会", "2026-07-18", "2026-05-31 10:00", "学校説明会", "10:00-", "https://www.sakaehigashi.ed.jp/exam/j_event.html"),
            event("入試説明会", "2026-11-21", "2026-10-12 10:00", "入試説明会", "10:00-", "https://www.sakaehigashi.ed.jp/exam/j_event.html"),
        ],
        "exam_sessions": [
            exam_session("sakae-higashi-dec10-am", "東大・難関大クラス 12月入試", "2026-12-10", "AM", 54, 50, source_url="https://www.sakaehigashi.ed.jp/exam/", note="ユーザー例に基づく日付。公式募集要項で要確認"),
            exam_session("sakae-higashi-jan11-am-todai", "東大特待4科", "2027-01-11", "AM", 59, 57, source_url="https://www.sakaehigashi.ed.jp/exam/"),
            exam_session("sakae-higashi-jan12-pm-math", "東大特待算数1科", "2027-01-12", "PM", 59, 58, source_url="https://www.sakaehigashi.ed.jp/exam/"),
            exam_session("sakae-higashi-jan16-am-nankan", "難関大クラス", "2027-01-16", "AM", 52, 48, source_url="https://www.sakaehigashi.ed.jp/exam/"),
        ],
        "notes": "12月入試の回次名・日付はユーザー例を優先入力。公式募集要項で最優先校対。",
    },
    {
        "id": "waseda-jitsugyo",
        "name": "早稲田実業学校中等部",
        "hensachi": 58,
        "hensachi_basis": "SAPIX女子80%候補値",
        "address": "東京都国分寺市本町1-2-1",
        "type": "共学",
        "nearest_station": "国分寺駅",
        "travel_time_from_koshigaya_laketown": 82,
        "homepage_url": "https://www.wasedajg.ed.jp/",
        "photo_url": "https://www.wasedajg.ed.jp/wp/wp-content/themes/waseda/assets/images/common/ogp.jpg",
        "photo_source_url": "https://www.wasedajg.ed.jp/",
        "description": "早稲田大学系属校として、初等部・中等部・高等部を置き、豊かな学識と表現力を持つ次世代のリーダー育成を掲げる学校。",
        "tags": ["大学附属", "英語教育", "探究学習", "中高一貫", "進学実績"],
        "events": [
            event("オープンスクール", "2026-07-11", "詳細後日掲載", "オープンスクール", "10:00-15:30", "https://www.wasedajg.ed.jp/junior/exam-s/explain-s/"),
            event("いなほ祭", "2026-10-10", "詳細後日掲載", "文化祭", "10:00-16:00", "https://www.wasedajg.ed.jp/junior/exam-s/explain-s/"),
            event("いなほ祭", "2026-10-11", "詳細後日掲載", "文化祭", "10:00-16:00", "https://www.wasedajg.ed.jp/junior/exam-s/explain-s/"),
            event("中等部 学校説明会", "2026-10-18", "詳細後日掲載", "学校説明会", "13:00 / 14:30", "https://www.wasedajg.ed.jp/junior/exam-s/explain-s/"),
            event("中等部 学校説明会", "2026-10-25", "詳細後日掲載", "学校説明会", "9:30 / 11:00", "https://www.wasedajg.ed.jp/junior/exam-s/explain-s/"),
        ],
        "exam_sessions": [
            exam_session("waseda-jitsugyo-feb01-full", "中等部入試", "2027-02-01", "FULL", 58, 55, "2026-12-20", "2027-01-10", "https://www.wasedajg.ed.jp/junior/exam-s/application-s/", "公式日程確認・偏差値要校対", "試験時間帯は仮にFULL。実際の拘束時間は要確認"),
        ],
        "notes": "試験日は公式募集概要で確認済み。SAPIX回次表示はユーザー校対待ち。",
    },
    {
        "id": "hiroo-koishikawa",
        "name": "広尾学園小石川中学校",
        "hensachi": 57,
        "hensachi_basis": "SAPIX女子80%最高値",
        "address": "東京都文京区本駒込2-29-1",
        "type": "共学",
        "nearest_station": "千石駅",
        "travel_time_from_koshigaya_laketown": 58,
        "homepage_url": "https://hiroo-koishikawa.ed.jp/",
        "photo_url": "https://hiroo-koishikawa.ed.jp/hk/wp-content/themes/hk/assets/img/top/kv01.jpg",
        "photo_source_url": "https://hiroo-koishikawa.ed.jp/",
        "description": "インターナショナルコースと本科コースを設け、英語で学ぶ環境、キャリア教育、海外プログラムを重視する中高一貫校。",
        "tags": ["国際化", "英語教育", "留学機会", "探究学習", "中高一貫"],
        "events": [
            event("第1回中学授業体験会", "2026-06-20", "2026-06-01 10:00", "授業体験会", "9:30 / 14:00", "https://hiroo-koishikawa.ed.jp/exam/junior-consultation"),
            event("第2回中学授業体験会", "2026-09-12", "受付開始待ち", "授業体験会", "9:30 / 14:00", "https://hiroo-koishikawa.ed.jp/exam/junior-consultation", "要再確認"),
            event("学校説明会", "2026-10-10", "受付開始待ち", "学校説明会", "10:00", "https://hiroo-koishikawa.ed.jp/exam/junior-consultation", "要再確認"),
            event("第1回入試傾向説明会", "2026-11-07", "受付開始待ち", "入試傾向説明会", "午前 / 午後", "https://hiroo-koishikawa.ed.jp/exam/junior-consultation", "要再確認"),
            event("第2回入試傾向説明会", "2026-12-05", "受付開始待ち", "入試傾向説明会", "午前", "https://hiroo-koishikawa.ed.jp/exam/junior-consultation", "要再確認"),
        ],
        "exam_sessions": [
            exam_session("hiroo-koishikawa-feb01-am-1", "第1回", "2027-02-01", "AM", 51, 49, source_url="https://hiroo-koishikawa.ed.jp/exam/junior-nyushi"),
            exam_session("hiroo-koishikawa-feb01-pm-2", "第2回", "2027-02-01", "PM", 55, 52, source_url="https://hiroo-koishikawa.ed.jp/exam/junior-nyushi"),
            exam_session("hiroo-koishikawa-feb02-pm-3", "第3回", "2027-02-02", "PM", 56, 53, source_url="https://hiroo-koishikawa.ed.jp/exam/junior-nyushi"),
            exam_session("hiroo-koishikawa-feb03-pm-4", "第4回", "2027-02-03", "PM", 57, 55, source_url="https://hiroo-koishikawa.ed.jp/exam/junior-nyushi"),
        ],
        "notes": "説明会は公式ページ候補。2027募集要項公開後に試験日程・出願期間を更新。",
    },
    {
        "id": "mita-international",
        "name": "三田国際科学学園中学校",
        "hensachi": 57,
        "hensachi_basis": "SAPIX女子80%最高値",
        "address": "東京都世田谷区用賀2-16-1",
        "type": "共学",
        "nearest_station": "用賀駅",
        "travel_time_from_koshigaya_laketown": 75,
        "homepage_url": "https://www.mita-is.ed.jp/",
        "photo_url": "https://www.mita-is.ed.jp/wp-content/themes/mita-is-theme/assets/is_img.png",
        "photo_source_url": "https://www.mita-is.ed.jp/",
        "description": "「世界標準の教育」を実践し、インターナショナルサイエンスクラス、メディカルサイエンステクノロジークラスなどを設置する学校。",
        "tags": ["国際化", "英語教育", "留学機会", "サイエンス", "中高一貫"],
        "events": [
            event("学校説明会", "2026-06-20", "2026-05-21 12:00", "学校説明会", "未定", "https://www.mita-is.ed.jp/admissions/visits/"),
            event("学校説明会", "2026-07-11", "約1ヶ月前", "学校説明会", "未定", "https://www.mita-is.ed.jp/admissions/visits/"),
            event("学校説明会", "2026-07-25", "約1ヶ月前", "学校説明会", "未定", "https://www.mita-is.ed.jp/admissions/visits/"),
            event("入試傾向説明会", "2026-10-10", "準備中", "入試傾向説明会", "未定", "https://www.mita-is.ed.jp/admissions/visits/"),
            event("入試傾向説明会", "2026-11-14", "準備中", "入試傾向説明会", "未定", "https://www.mita-is.ed.jp/admissions/visits/"),
            event("MITA International Festival 2026", "2026-10-31", "準備中", "文化祭", "10/31・11/1", "https://www.mita-is.ed.jp/admissions/visits/"),
        ],
        "exam_sessions": [
            exam_session("mita-international-feb01-am-isc", "第1回 ISC", "2027-02-01", "AM", 49, 48, source_url="https://www.mita-is.ed.jp/admissions/regular/"),
            exam_session("mita-international-feb01-am-ic", "第1回 IC", "2027-02-01", "AM", 47, 46, source_url="https://www.mita-is.ed.jp/admissions/regular/"),
            exam_session("mita-international-feb02-am-isc", "第2回 ISC", "2027-02-02", "AM", 57, 56, source_url="https://www.mita-is.ed.jp/admissions/regular/"),
            exam_session("mita-international-feb02-am-ic", "第2回 IC", "2027-02-02", "AM", 52, 49, source_url="https://www.mita-is.ed.jp/admissions/regular/"),
            exam_session("mita-international-feb03-am-isc", "第3回 ISC", "2027-02-03", "AM", 55, 52, source_url="https://www.mita-is.ed.jp/admissions/regular/"),
            exam_session("mita-international-feb03-am-ic", "第3回 IC", "2027-02-03", "AM", 51, 48, source_url="https://www.mita-is.ed.jp/admissions/regular/"),
            exam_session("mita-international-feb04-pm-mst", "MST入試", "2027-02-04", "PM", 55, 53, source_url="https://www.mita-is.ed.jp/admissions/regular/"),
            exam_session("mita-international-feb05-pm-4", "第4回", "2027-02-05", "PM", 54, 53, source_url="https://www.mita-is.ed.jp/admissions/regular/"),
        ],
        "notes": "学校説明会は公式ページ確認済み。2027一般入試要項公開後に出願期間を更新。",
    },
    {
        "id": "kaichi-nihonbashi",
        "name": "開智日本橋学園中学校",
        "hensachi": 52,
        "hensachi_basis": "SAPIX女子80%最高値",
        "address": "東京都中央区日本橋馬喰町2-7-6",
        "type": "共学",
        "nearest_station": "浅草橋駅",
        "travel_time_from_koshigaya_laketown": 46,
        "homepage_url": "https://www.kng.ed.jp/",
        "photo_url": "https://kng.ed.jp/wp-content/uploads/2025/11/IB-Discovery-2.png",
        "photo_source_url": "https://www.kng.ed.jp/",
        "description": "探究型の学び、国際バカロレアの教育手法、英語を使う環境を特色とする都心型の中高一貫校。",
        "tags": ["国際化", "英語教育", "探究学習", "中高一貫"],
        "events": [
            event("第4回学校説明会", "2026-01-10", "2025-12-10", "学校説明会", "10:30 / 12:30", "https://kng.ed.jp/schedule/", "参考", "2026年度参考。新年度日程公開後に更新"),
            event("中学入試報告会", "2026-02-28", "2026-01-28 18:00", "入試報告会", "10:30 / 12:30", "https://kng.ed.jp/schedule/", "参考", "2026年度参考。新年度日程公開後に更新"),
        ],
        "exam_sessions": [
            exam_session("kaichi-nihonbashi-feb01-am-1", "第1回", "2027-02-01", "AM", 46, 42, source_url="https://kng.ed.jp/admission/"),
            exam_session("kaichi-nihonbashi-feb01-pm-2", "第2回", "2027-02-01", "PM", 51, 47, source_url="https://kng.ed.jp/admission/"),
            exam_session("kaichi-nihonbashi-feb02-pm-3", "第3回", "2027-02-02", "PM", 49, 45, source_url="https://kng.ed.jp/admission/"),
            exam_session("kaichi-nihonbashi-feb03-am-4", "第4回", "2027-02-03", "AM", 47, 44, source_url="https://kng.ed.jp/admission/"),
            exam_session("kaichi-nihonbashi-feb03-pm-math", "特待生算数単科", "2027-02-03", "PM", 52, 51, source_url="https://kng.ed.jp/admission/"),
            exam_session("kaichi-nihonbashi-feb04-pm-scholar4", "特待生4科", "2027-02-04", "PM", 49, 47, source_url="https://kng.ed.jp/admission/"),
            exam_session("kaichi-nihonbashi-feb05-am-heigan", "併願", "2027-02-05", "AM", 42, 38, source_url="https://kng.ed.jp/admission/"),
        ],
        "notes": "イベントは参考年度。最新イベント日程の公開後に月次更新。",
    },
    {
        "id": "kaichi",
        "name": "開智中学・高等学校",
        "hensachi": 51,
        "hensachi_basis": "SAPIX女子80%最高値",
        "address": "埼玉県さいたま市岩槻区徳力186",
        "type": "共学",
        "nearest_station": "東岩槻駅",
        "travel_time_from_koshigaya_laketown": 48,
        "homepage_url": "https://ikkanbu.kaichigakuen.ed.jp/",
        "photo_url": "https://ikkanbu.kaichigakuen.ed.jp/wp-content/uploads/2026/05/%E4%BD%93%E8%82%B2%E7%A5%AD1-250x250.jpg",
        "photo_source_url": "https://ikkanbu.kaichigakuen.ed.jp/",
        "description": "創発クラスと4コース、探究、フィールドワーク、ICT活用、国際バカロレア、国際英語教育などを掲げる中高一貫校。",
        "tags": ["探究学習", "理科強", "英語教育", "中高一貫", "国際化"],
        "events": [
            event("学校説明会", "2026-06-07", "2026-05-18", "学校説明会", "未定", "https://ikkanbu.kaichigakuen.ed.jp/admission/", "要再確認"),
            event("体験授業", "2026-08-23", "2026-07-30", "体験授業", "未定", "https://ikkanbu.kaichigakuen.ed.jp/admission/", "要再確認"),
        ],
        "exam_sessions": [
            exam_session("kaichi-jan10-am-souhatsu", "創発クラス特待A", "2027-01-10", "AM", 51, 48, source_url="https://ikkanbu.kaichigakuen.ed.jp/admission/"),
            exam_session("kaichi-jan11-am-math", "算数特待", "2027-01-11", "AM", 51, 50, source_url="https://ikkanbu.kaichigakuen.ed.jp/admission/"),
            exam_session("kaichi-jan12-am-1", "1回", "2027-01-12", "AM", 42, 38, source_url="https://ikkanbu.kaichigakuen.ed.jp/admission/"),
        ],
        "notes": "2027年度公式募集要項公開後に出願期間・回次名を再確認。",
    },
]


def apply_average_hensachi(schools):
    for school in schools:
        values = [
            float(session["sapix_girls_80"])
            for session in school.get("exam_sessions", [])
            if session.get("sapix_girls_80") is not None
        ]
        if not values:
            continue
        average = round(sum(values) / len(values), 1)
        school["hensachi"] = int(average) if average.is_integer() else average
        school["hensachi_basis"] = "SAPIX女子80% 回次平均"


apply_average_hensachi(SCHOOLS)
SCHOOLS = sorted(SCHOOLS, key=lambda school: school["hensachi"], reverse=True)
